version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 15
  pre_build: 
    commands:
      - echo Will check node and npm versions
      - node -v
      - npm -v
      - echo Installing npm dependencies
      - npm install
  build: 
    commands:
      - echo Build Started
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'

  
    
